name: Performance Audit
on:
  schedule:
    - cron: '0 2 * * *' # Run daily at 2 AM
  workflow_dispatch: # Allow manual trigger

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Start app
        run: npm run dev &
      - name: Wait for app
        run: npx wait-on http://localhost:3000
      - name: Performance tests
        run: npx playwright test tests/e2e/perf.spec.ts --project=desktop-chromium
      - name: Upload performance report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: playwright-report
